# Path to downloaded vicon SDK module 
vicon_sdk_path: 'C:\Program Files\Vicon\DataStream SDK\Win64\Python'

# Hot keys which the pedals are mapped to
keys:
  start: 'r'
  stop: 'e'
  save: 's'


# Shogun
shogun_hostname:  'localhost'

# Live Link Face
llf_udp_ip: '192.168.0.208'
llf_udp_port: 8000

llf_ip: '145.100.134.165'
llf_port: 6000