# Hot keys which the pedals are mapped to
keys:
  start: 'r'
  stop: 'e'
  save: 's'
  battery: 'b'

# Path to the folder where the data is saved
output_dir: output



# Shogun
shogun_hostname:  'localhost'

# Live Link Face
llf_udp_ip: "192.168.0.153"
llf_udp_port: 8006

# Local computer 
target_ip: '192.168.0.180' #'192.168.0.161'
# '145.100.134.165'
target_port: 8005



# Path to downloaded vicon SDK module 
vicon_sdk_path: 'C:\Program Files\Vicon\DataStream SDK\Win64\Python'
