# Hot keys which the pedals are mapped to
keys:
  start: 'r'
  stop: 'e'
  save: 's'
  battery: 'b'
  quit: 'q'

# Path to the folder where the data is saved
output_dir: output



# Shogun
shogun_hostname:  'localhost'
shogun_port: 52800

# Live Link Face
llf_udp_ip: "192.168.0.246"
llf_udp_port: 8006

# Local computer 
target_ip: '192.168.0.180'
target_port: 8005
tcp_iphone_port: 8007
controller_port: 8008

# Websocket
websock_ip: '192.168.0.180'
websock_port: 8009

# Path to downloaded vicon SDK module 
vicon_sdk_path: 'C:\Program Files\Vicon\DataStream SDK\Win64\Python'
